FROM ubuntu:20.04

USER root

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-psycopg2

WORKDIR /tmp

## requirements for the backend python package
COPY setup.py .
RUN python3 setup.py egg_info
RUN pip3 install -r *.egg-info/requires.txt

## copy entry points into /app/dev/
WORKDIR /app
COPY docker/dev ./dev
## code will be edited live at /app/mount/
