"""yet another revision

Revision ID: 382803ffe419
Revises: 
Create Date: 2024-03-25 08:22:13.686786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382803ffe419'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.NCHAR(length=36), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person'))
    )
    op.create_index(op.f('ix_person_id'), 'person', ['id'], unique=False)
    op.create_table('userinterface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.NCHAR(length=36), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userinterface'))
    )
    op.create_index(op.f('ix_userinterface_id'), 'userinterface', ['id'], unique=False)
    op.create_table('adminuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['userinterface.id'], name=op.f('fk_adminuser_id_userinterface')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adminuser'))
    )
    op.create_table('masteruser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['userinterface.id'], name=op.f('fk_masteruser_id_userinterface')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_masteruser'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extradata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['userinterface.id'], name=op.f('fk_user_id_userinterface')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('masteruser')
    op.drop_table('adminuser')
    op.drop_index(op.f('ix_userinterface_id'), table_name='userinterface')
    op.drop_table('userinterface')
    op.drop_index(op.f('ix_person_id'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
