"""yet another revision

Revision ID: 80fb5b0022ff
Revises: fef2852a27de
Create Date: 2024-03-25 08:41:21.746593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fb5b0022ff'
down_revision = 'fef2852a27de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
