"""yet another revision

Revision ID: e6e7974080d4
Revises: 382803ffe419
Create Date: 2024-03-25 08:22:28.547815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e7974080d4'
down_revision = '382803ffe419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
