"""yet another revision

Revision ID: fef2852a27de
Revises: e6e7974080d4
Create Date: 2024-03-25 08:30:51.476932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef2852a27de'
down_revision = 'e6e7974080d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
